function getChatGPTDeliveryCore(){
const V="9.1.0",C={ROOT:"ChatGPT Delivery",OUT:"À envoyer",SENT:"Envoyé",FAIL:"Échecs",REC:"Reçus",IN:"Inbox Telegram",XL:"XL Jobs",CATS:["Applications-APK","PDF","Documents","Images","Archives","Audio-Video","Données","Autres"],CHAT:"1298744015",INMAX:19922944,OUTMAX:47185920};
const P=()=>PropertiesService.getScriptProperties(),T=()=>{const x=P().getProperty("TELEGRAM_BOT_TOKEN");if(!x)throw Error("TELEGRAM_BOT_TOKEN absent");return x},A=m=>"https://api.telegram.org/bot"+T()+"/"+m;
function tg(m,p){const r=UrlFetchApp.fetch(A(m),{method:"post",payload:p||{},muteHttpExceptions:true}),d=JSON.parse(r.getContentText());if(!d.ok)throw Error("Telegram "+m+": "+(d.description||r.getResponseCode()));return d}
function get(m,p){const q=Object.keys(p||{}).map(k=>encodeURIComponent(k)+"="+encodeURIComponent(p[k])).join("&"),r=UrlFetchApp.fetch(A(m)+(q?"?"+q:""),{muteHttpExceptions:true}),d=JSON.parse(r.getContentText());if(!d.ok)throw Error("Telegram "+m+": "+(d.description||r.getResponseCode()));return d}
function retry(fn){let e;for(let i=0;i<4;i++){try{return fn()}catch(x){e=x;if(!/(429|500|502|503|504|timeout|temporar|too many)/i.test(String(x)))throw x;Utilities.sleep(Math.min(1000*Math.pow(2,i),8000))}}throw e}
function child(p,n,c){const it=p.getFoldersByName(n);if(it.hasNext())return it.next();if(c)return p.createFolder(n);throw Error("Dossier manquant: "+n)}
function root(c){const id=P().getProperty("ROOT_FOLDER_ID");if(id)try{return DriveApp.getFolderById(id)}catch(e){}const it=DriveApp.getFoldersByName(C.ROOT),f=it.hasNext()?it.next():(c?DriveApp.createFolder(C.ROOT):null);if(!f)throw Error("Racine absente");P().setProperty("ROOT_FOLDER_ID",f.getId());return f}
function tree(){const r=root(true);[C.OUT,C.SENT,C.FAIL,C.REC,C.IN,C.XL].forEach(n=>child(r,n,true));[C.OUT,C.SENT,C.FAIL].forEach(b=>C.CATS.forEach(c=>child(child(r,b,true),c,true)));return r}
function rec(o){o.v=V;o.ts=new Date().toISOString();try{child(root(true),C.REC,true).createFile(Date.now()+"-"+String(o.filename||o.status||"event").replace(/[^a-zA-Z0-9._-]/g,"_")+".json",JSON.stringify(o,null,2),MimeType.PLAIN_TEXT)}catch(e){}P().setProperty("JOURNAL_"+Date.now()+"_"+Math.floor(Math.random()*9999),JSON.stringify(o).slice(0,8000))}
function menu(){return JSON.stringify({inline_keyboard:[[{text:"📥 Vers ChatGPT",callback_data:"v9:in"},{text:"📤 Livraisons",callback_data:"v9:out"}],[{text:"🧩 XL",callback_data:"v9:xl"},{text:"♻️ Renvoyer",callback_data:"v9:resend"}],[{text:"📚 Historique",callback_data:"v9:hist"},{text:"📡 Santé",callback_data:"v9:health"}],[{text:"❓ Aide",callback_data:"v9:help"}]]})}
function send(s){return retry(()=>tg("sendMessage",{chat_id:C.CHAT,text:s,parse_mode:"HTML",reply_markup:menu()}))}
function setup(){tree();P().setProperty("TELEGRAM_CHAT_ID",C.CHAT);retry(()=>get("getChat",{chat_id:C.CHAT}));try{get("deleteWebhook",{drop_pending_updates:false})}catch(e){}tg("setMyCommands",{commands:JSON.stringify([{command:"start",description:"Portail"},{command:"inbox",description:"Vers ChatGPT"},{command:"latest",description:"Dernière livraison"},{command:"xl",description:"Gros fichiers"},{command:"health",description:"Santé"},{command:"help",description:"Aide"}])});if(!ScriptApp.getProjectTriggers().some(x=>x.getHandlerFunction()==="processDelivery"))ScriptApp.newTrigger("processDelivery").timeBased().everyMinutes(1).create();send("✨ <b>ChatGPT Delivery V9.1</b>\nPortail bidirectionnel actif.");process();return{ok:true,v:V}}
function process(){tree();const l=LockService.getScriptLock();if(!l.tryLock(500))return{busy:true};try{updates();outbox();return{ok:true,v:V}}finally{l.releaseLock()}}
function updates(){const off=Number(P().getProperty("TG_OFFSET")||0),d=retry(()=>get("getUpdates",{offset:off,limit:50,timeout:0}));let n=off;(d.result||[]).forEach(u=>{n=Math.max(n,Number(u.update_id)+1);if(u.callback_query)return cb(u.callback_query);if(u.message&&String(u.message.chat.id)===C.CHAT)msg(u.message)});if(n!==off)P().setProperty("TG_OFFSET",String(n))}
function cb(q){try{tg("answerCallbackQuery",{callback_query_id:q.id})}catch(e){}const a=String(q.data||"").replace("v9:","");if(a==="resend")return resend();panel(a)}
function msg(m){const t=String(m.text||"").toLowerCase();if(t==="/start"||t==="/menu")return panel("home");if(t==="/inbox")return panel("in");if(t==="/latest")return panel("out");if(t==="/xl")return panel("xl");if(t==="/health")return panel("health");if(t==="/help")return panel("help");const z=media(m);if(z)ingest(m,z)}
function media(m){if(m.document)return["document",m.document,m.document.file_name||"document"];if(m.video)return["video",m.video,m.video.file_name||"video.mp4"];if(m.audio)return["audio",m.audio,m.audio.file_name||"audio.mp3"];if(m.voice)return["voice",m.voice,"voice.ogg"];if(m.photo&&m.photo.length)return["photo",m.photo[m.photo.length-1],"photo.jpg"];return null}
function ingest(m,z){const o=z[1],size=Number(o.file_size||0),uid=o.file_unique_id||"",key="IN_"+uid+"_"+m.message_id;if(P().getProperty(key))return;const meta={dir:"IN",kind:z[0],filename:z[2],size_bytes:size,file_id:o.file_id,file_unique_id:uid,message_id:m.message_id};if(size>0&&size<=C.INMAX){try{const f=retry(()=>get("getFile",{file_id:o.file_id})),r=retry(()=>UrlFetchApp.fetch("https://api.telegram.org/file/bot"+T()+"/"+f.result.file_path,{muteHttpExceptions:true}));if(r.getResponseCode()!==200)throw Error("download "+r.getResponseCode());const b=r.getBlob().setName(z[2]),df=child(root(true),C.IN,true).createFile(b);meta.status="READY_FOR_CHATGPT";meta.drive_file_id=df.getId();rec(meta);P().setProperty(key,"1");send("📥 <b>Reçu pour ChatGPT</b>\n"+z[2])}catch(e){meta.status="RETRY_PENDING";meta.error=String(e);rec(meta)}}else{meta.status="XL_PENDING";meta.strategy="MTProto_or_resumable_MiniApp";rec(meta);P().setProperty("XL_LAST",JSON.stringify(meta));P().setProperty(key,"1");send("🧩 <b>Gros fichier conservé</b>\n"+z[2]+"\nJob XL créé; inutile de renvoyer.")}}
function outbox(){const o=child(root(true),C.OUT,true);C.CATS.forEach(cat=>{const it=child(o,cat,true).getFiles();let k=0;while(it.hasNext()&&k++<8){const f=it.next();try{deliver(f,cat)}catch(e){const s=String(e);rec({dir:"OUT",status:/429|50[0-4]|timeout|temporar/i.test(s)?"RETRY_PENDING":"FAILED",filename:f.getName(),error:s});if(!/429|50[0-4]|timeout|temporar/i.test(s))try{f.moveTo(child(child(root(true),C.FAIL,true),cat,true))}catch(_){}}}})}
function deliver(f,cat){const id=f.getId(),key="OUT_"+id;if(P().getProperty(key)){try{f.moveTo(child(child(root(true),C.SENT,true),cat,true))}catch(e){}return}if(f.getSize()>C.OUTMAX)throw Error("XL_REQUIRED >45MiB");const b=drive(f).setName(f.getName()),h=sha(b.getBytes()),d=retry(()=>tg("sendDocument",{chat_id:C.CHAT,document:b,caption:"📦 "+f.getName()+"\nSHA-256 "+h.slice(0,16)+"…"})),fid=d.result.document&&d.result.document.file_id||"";P().setProperty(key,JSON.stringify({message_id:d.result.message_id,file_id:fid,sha256:h}));P().setProperty("LAST_OUT",JSON.stringify({filename:f.getName(),file_id:fid,sha256:h}));rec({dir:"OUT",status:"DELIVERED",filename:f.getName(),telegram_file_id:fid,sha256:h});f.moveTo(child(child(root(true),C.SENT,true),cat,true))}
function drive(f){const r=UrlFetchApp.fetch("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(f.getId())+"?alt=media",{headers:{Authorization:"Bearer "+ScriptApp.getOAuthToken()},muteHttpExceptions:true});if(r.getResponseCode()!==200)throw Error("Drive "+r.getResponseCode());return r.getBlob()}
function resend(){const x=JSON.parse(P().getProperty("LAST_OUT")||"{}");if(!x.file_id)return send("Aucune livraison réutilisable.");tg("sendDocument",{chat_id:C.CHAT,document:x.file_id,caption:"♻️ "+x.filename});rec({dir:"OUT",status:"RESENT_FROM_TELEGRAM_CACHE",filename:x.filename})}
function panel(v){let s="🏠 <b>ChatGPT Delivery V9.1</b>";if(v==="health")s="📡 <b>Santé</b>\n✅ Bot\n✅ Core auto-update/cache/rollback\n✅ Anti-doublon\nDrive: "+(safe()?"✅":"⚠️ dégradé");if(v==="in")s="📥 <b>Vers ChatGPT</b>\n≤19 MiB: ingestion auto.\n>19 MiB: job XL durable.";if(v==="out")s="📤 <b>Livraisons</b>\nDernier: "+last();if(v==="xl")s="🧩 <b>XL</b>\nSortie: segmentation ≤44 MiB ou backend XL.\nEntrée: MTProto/Local Bot API ou Mini App résumable.";if(v==="hist")s="📚 <b>Historique</b>\nJournal double Drive + local.";if(v==="help")s="❓ <b>Aide</b>\nDans ChatGPT: « envoie sur Telegram ».\nIci: envoie un fichier pour ChatGPT.";send(s)}
function safe(){try{tree();return true}catch(e){return false}}function last(){try{return JSON.parse(P().getProperty("LAST_OUT")||"{}").filename||"aucune"}catch(e){return"aucune"}}function sha(a){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,a).map(b=>("0"+((b<0?b+256:b).toString(16))).slice(-2)).join("")}
return{version:V,setup:setup,process:process,status:()=>({version:V,drive:safe(),last:last()})}}
